using System.Diagnostics.CodeAnalysis;
using Silksong.BingoSync.Data;
using Silksong.BingoSync.Exceptions;

namespace Silksong.BingoSync.Extensions;

/// <summary>
/// Extension methods of <see cref="PlayerData"/> concerning journal entries
/// </summary>
[SuppressMessage("ReSharper", "ConvertToExtensionBlock")]
public static partial class PlayerDataExtensions
{
	/// <summary>
	/// Gets the <see cref="EnemyJournalKillData.KillData"/> of the given key
	/// </summary>
	private static EnemyJournalKillData.KillData GetKillData(this PlayerData data, string key) =>
		data.EnemyJournalKillData.GetKillData(key);

	/// <summary>
	/// Gets the amount of kills of the journal entry of the given key
	/// </summary>
	private static int GetKillCount(this PlayerData data, string key) =>
		data.GetKillData(key).Kills;

	/// <summary>
	/// Checks if a journal entry is set for the given key
	/// </summary>
	private static bool HasJournalEntry(this PlayerData data, string key) =>
		data.GetKillCount(key) > 0;

	/// <summary>
	/// Checks if the journal entry of the given <see cref="Boss"/> has been obtained
	/// </summary>
	public static bool HasJournalEntry(this PlayerData data, Boss boss)
	{
		return boss switch
		{
			Boss.Shakra => data.HasJournalEntry("Shakra"),
			Boss.BellBeast => throw new NotImplementedException(),
			Boss.FourthChorus => throw new NotImplementedException(),
			Boss.GreatConchflies => throw new NotImplementedException(),
			Boss.Lace1 => throw new NotImplementedException(),
			Boss.LastJudge => throw new NotImplementedException(),
			Boss.Moorwing => throw new NotImplementedException(),
			Boss.MossMother => data.HasJournalEntry("Mossbone Mother"),
			Boss.MossMothers => data.GetKillCount("Mossbone Mother") >= 3,
			Boss.Phantom => throw new NotImplementedException(),
			Boss.SavageBeastfly1 => throw new NotImplementedException(),
			Boss.SisterSplinter => throw new NotImplementedException(),
			Boss.SkullTyrant1 => data.HasJournalEntry("Skull King"),
			Boss.SkullTyrant2 => data.GetKillCount("Skull King") >= 2,
			Boss.Widow => throw new NotImplementedException(),
			Boss.Broodmother => throw new NotImplementedException(),
			Boss.CogworkDancers => throw new NotImplementedException(),
			Boss.DisgracedChefLugoli => throw new NotImplementedException(),
			Boss.FatherOfTheFlame => throw new NotImplementedException(),
			Boss.FirstSinner => throw new NotImplementedException(),
			Boss.Forebrothers => throw new NotImplementedException(),
			Boss.Garmond => data.HasJournalEntry("Garmond"),
			Boss.GrandMotherSilk => throw new NotImplementedException(),
			Boss.Groal => throw new NotImplementedException(),
			Boss.Lace2 => throw new NotImplementedException(),
			Boss.RagingConchfly => throw new NotImplementedException(),
			Boss.SavageBeastfly2 => throw new NotImplementedException(),
			Boss.SecondSentinel => throw new NotImplementedException(),
			Boss.TheUnravelled => throw new NotImplementedException(),
			Boss.Trobbio => throw new NotImplementedException(),
			Boss.Voltvyrm => throw new NotImplementedException(),
			Boss.BellEater => data.HasJournalEntry("Giant Centipede"),
			Boss.CloverDancers => throw new NotImplementedException(),
			Boss.Crawfather => throw new NotImplementedException(),
			Boss.CrustKingKhann => throw new NotImplementedException(),
			Boss.GurrTheOutcast => throw new NotImplementedException(),
			Boss.LostGarmond => throw new NotImplementedException(),
			Boss.LostLace => throw new NotImplementedException(),
			Boss.Nyleth => throw new NotImplementedException(),
			Boss.Palestag => throw new NotImplementedException(),
			Boss.Pinstress => data.HasJournalEntry("Pinstress Boss"),
			Boss.PlasmifiedZango => throw new NotImplementedException(),
			Boss.ShrineGuardianSeth => throw new NotImplementedException(),
			Boss.SkarrsingerKarmelita => throw new NotImplementedException(),
			Boss.TormentedTrobbio => throw new NotImplementedException(),
			Boss.Watcher => throw new NotImplementedException(),
			_ => throw new InvalidCheckException<Boss>(boss),
		};
	}

	/// <summary>
	/// Checks if the journal entry of the given <see cref="Enemy"/> has been obtained
	/// </summary>
	public static bool HasJournalEntry(this PlayerData data, Enemy enemy)
	{
		return enemy switch
		{
			Enemy.Mossgrub => throw new NotImplementedException(),
			Enemy.MassiveMossgrub => throw new NotImplementedException(),
			Enemy.Mossmir => throw new NotImplementedException(),
			Enemy.Aknid => throw new NotImplementedException(),
			Enemy.SkullScuttler => throw new NotImplementedException(),
			Enemy.Skullwing => throw new NotImplementedException(),
			Enemy.SkullBrute => throw new NotImplementedException(),
			Enemy.Kilik => throw new NotImplementedException(),
			Enemy.Beastfly => throw new NotImplementedException(),
			Enemy.Caranid => throw new NotImplementedException(),
			Enemy.ViciousCaranid => throw new NotImplementedException(),
			Enemy.HardboneHopper => throw new NotImplementedException(),
			Enemy.HardboneElder => throw new NotImplementedException(),
			Enemy.Tarmite => throw new NotImplementedException(),
			Enemy.Mawling => throw new NotImplementedException(),
			Enemy.Marrowmaw => throw new NotImplementedException(),
			Enemy.Hoker => throw new NotImplementedException(),
			Enemy.Flintbeetle => throw new NotImplementedException(),
			Enemy.Rhinogrund => throw new NotImplementedException(),
			Enemy.Gromling => throw new NotImplementedException(),
			Enemy.Grom => throw new NotImplementedException(),
			Enemy.PilgrimGroveller => throw new NotImplementedException(),
			Enemy.PilgrimPouncer => throw new NotImplementedException(),
			Enemy.PilgrimHornfly => throw new NotImplementedException(),
			Enemy.PilgrimHulk => throw new NotImplementedException(),
			Enemy.WearyPilgrim => throw new NotImplementedException(),
			Enemy.PilgrimBellbearer => throw new NotImplementedException(),
			Enemy.WingedPilgrim => throw new NotImplementedException(),
			Enemy.ElderPilgrim => throw new NotImplementedException(),
			Enemy.WingedPilgrimBellbearer => throw new NotImplementedException(),
			Enemy.PilgrimHiker => throw new NotImplementedException(),
			Enemy.PilgrimGuide => throw new NotImplementedException(),
			Enemy.OvergrownPilgrim => throw new NotImplementedException(),
			Enemy.CovetousPilgrim => throw new NotImplementedException(),
			Enemy.Snitchfly => throw new NotImplementedException(),
			Enemy.Lavalug => throw new NotImplementedException(),
			Enemy.Lavalarga => throw new NotImplementedException(),
			Enemy.SmeltShoveller => throw new NotImplementedException(),
			Enemy.FlintstoneFlyer => throw new NotImplementedException(),
			Enemy.FlintflameFlyer => throw new NotImplementedException(),
			Enemy.SmokerockSifter => throw new NotImplementedException(),
			Enemy.DeepDiver => throw new NotImplementedException(),
			Enemy.Cragglite => throw new NotImplementedException(),
			Enemy.Craggler => throw new NotImplementedException(),
			Enemy.Brushflit => throw new NotImplementedException(),
			Enemy.Fertid => throw new NotImplementedException(),
			Enemy.FlappingFertid => throw new NotImplementedException(),
			Enemy.Skarrlid => throw new NotImplementedException(),
			Enemy.Skarrwing => throw new NotImplementedException(),
			Enemy.SkarrScout => throw new NotImplementedException(),
			Enemy.SkarrStalker => throw new NotImplementedException(),
			Enemy.SpearSkarr => throw new NotImplementedException(),
			Enemy.Skarrgard => throw new NotImplementedException(),
			Enemy.LastClaw => throw new NotImplementedException(),
			Enemy.Mite => throw new NotImplementedException(),
			Enemy.Fluttermite => throw new NotImplementedException(),
			Enemy.Mitemother => throw new NotImplementedException(),
			Enemy.DregCatcher => throw new NotImplementedException(),
			Enemy.SilkSnipper => throw new NotImplementedException(),
			Enemy.ThreadRaker => throw new NotImplementedException(),
			Enemy.Wisp => throw new NotImplementedException(),
			Enemy.BurningBug => throw new NotImplementedException(),
			Enemy.Craw => throw new NotImplementedException(),
			Enemy.Tallcraw => throw new NotImplementedException(),
			Enemy.Squatcraw => throw new NotImplementedException(),
			Enemy.CrawJuror => throw new NotImplementedException(),
			Enemy.TallcrawJuror => throw new NotImplementedException(),
			Enemy.SquatcrawJuror => throw new NotImplementedException(),
			Enemy.Muckmaggot => throw new NotImplementedException(),
			Enemy.Slubberlug => throw new NotImplementedException(),
			Enemy.Muckroach => throw new NotImplementedException(),
			Enemy.Bloatroach => throw new NotImplementedException(),
			Enemy.Roachcatcher => throw new NotImplementedException(),
			Enemy.Roachfeeder => throw new NotImplementedException(),
			Enemy.Roachkeeper => throw new NotImplementedException(),
			Enemy.Roachserver => throw new NotImplementedException(),
			Enemy.Wraith => throw new NotImplementedException(),
			Enemy.MothleafLagnia => throw new NotImplementedException(),
			Enemy.Miremite => throw new NotImplementedException(),
			Enemy.SwampSquit => throw new NotImplementedException(),
			Enemy.SpitSquit => throw new NotImplementedException(),
			Enemy.Stilkin => throw new NotImplementedException(),
			Enemy.StilkinTrapper => throw new NotImplementedException(),
			Enemy.Barnak => throw new NotImplementedException(),
			Enemy.Ductsucker => throw new NotImplementedException(),
			Enemy.PondSkipper => throw new NotImplementedException(),
			Enemy.Pondcatcher => throw new NotImplementedException(),
			Enemy.ShellwoodGnat => throw new NotImplementedException(),
			Enemy.WoodWasp => throw new NotImplementedException(),
			Enemy.Splinter => throw new NotImplementedException(),
			Enemy.Splinterhorn => throw new NotImplementedException(),
			Enemy.Splinterbark => throw new NotImplementedException(),
			Enemy.Phacia => throw new NotImplementedException(),
			Enemy.Pollenica => throw new NotImplementedException(),
			Enemy.Gahlia => throw new NotImplementedException(),
			Enemy.Furm => throw new NotImplementedException(),
			Enemy.WingedFurm => throw new NotImplementedException(),
			Enemy.Pharlid => throw new NotImplementedException(),
			Enemy.PharlidDiver => throw new NotImplementedException(),
			Enemy.Shardillard => throw new NotImplementedException(),
			Enemy.Sandcarver => throw new NotImplementedException(),
			Enemy.Squirrm => throw new NotImplementedException(),
			Enemy.Judge => throw new NotImplementedException(),
			Enemy.CoralFurm => throw new NotImplementedException(),
			Enemy.Driznit => throw new NotImplementedException(),
			Enemy.Driznarga => throw new NotImplementedException(),
			Enemy.Pokenabbin => throw new NotImplementedException(),
			Enemy.Conchfly => throw new NotImplementedException(),
			Enemy.Crustcrawler => throw new NotImplementedException(),
			Enemy.Crustcrag => throw new NotImplementedException(),
			Enemy.Kai => throw new NotImplementedException(),
			Enemy.SpinebeakKai => throw new NotImplementedException(),
			Enemy.SteelspineKai => throw new NotImplementedException(),
			Enemy.Yuma => throw new NotImplementedException(),
			Enemy.Yumama => throw new NotImplementedException(),
			Enemy.Karaka => throw new NotImplementedException(),
			Enemy.Kakri => throw new NotImplementedException(),
			Enemy.Yago => throw new NotImplementedException(),
			Enemy.KarakGor => throw new NotImplementedException(),
			Enemy.Alita => throw new NotImplementedException(),
			Enemy.CorrcrustKaraka => throw new NotImplementedException(),
			Enemy.Voltvyrm => throw new NotImplementedException(),
			Enemy.Drapefly => throw new NotImplementedException(),
			Enemy.Drapelord => throw new NotImplementedException(),
			Enemy.Drapemite => throw new NotImplementedException(),
			Enemy.GiantDrapemite => throw new NotImplementedException(),
			Enemy.Underworker => throw new NotImplementedException(),
			Enemy.Underscrub => throw new NotImplementedException(),
			Enemy.Undersweep => throw new NotImplementedException(),
			Enemy.Underpoke => throw new NotImplementedException(),
			Enemy.Underloft => throw new NotImplementedException(),
			Enemy.Undercrank => throw new NotImplementedException(),
			Enemy.Envoy => throw new NotImplementedException(),
			Enemy.ChoirPouncer => throw new NotImplementedException(),
			Enemy.ChoirHornhead => throw new NotImplementedException(),
			Enemy.ChoirBellbearer => throw new NotImplementedException(),
			Enemy.ChoirFlyer => throw new NotImplementedException(),
			Enemy.ChoirElder => throw new NotImplementedException(),
			Enemy.Choristor => throw new NotImplementedException(),
			Enemy.Reed => throw new NotImplementedException(),
			Enemy.GrandReed => throw new NotImplementedException(),
			Enemy.ChoirClapper => throw new NotImplementedException(),
			Enemy.Clawmaiden => throw new NotImplementedException(),
			Enemy.Memoria => throw new NotImplementedException(),
			Enemy.Minister => throw new NotImplementedException(),
			Enemy.Maestro => throw new NotImplementedException(),
			Enemy.DregHusk => throw new NotImplementedException(),
			Enemy.Dregwheel => throw new NotImplementedException(),
			Enemy.Surgeon => throw new NotImplementedException(),
			Enemy.Mortician => throw new NotImplementedException(),
			Enemy.CogworkUnderfly => throw new NotImplementedException(),
			Enemy.CogworkHauler => throw new NotImplementedException(),
			Enemy.CogworkCrawler => throw new NotImplementedException(),
			Enemy.Cogworker => throw new NotImplementedException(),
			Enemy.CogworkSpine => throw new NotImplementedException(),
			Enemy.CogworkChoirbug => throw new NotImplementedException(),
			Enemy.CogworkCleanser => throw new NotImplementedException(),
			Enemy.CogworkDefender => throw new NotImplementedException(),
			Enemy.CogworkClapper => throw new NotImplementedException(),
			Enemy.Vaultborn => throw new NotImplementedException(),
			Enemy.Lampbearer => throw new NotImplementedException(),
			Enemy.Scrollreader => throw new NotImplementedException(),
			Enemy.Vaultkeeper => throw new NotImplementedException(),
			Enemy.Penitent => throw new NotImplementedException(),
			Enemy.PunyPenitent => throw new NotImplementedException(),
			Enemy.Freshfly => throw new NotImplementedException(),
			Enemy.Scabfly => throw new NotImplementedException(),
			Enemy.Guardfly => throw new NotImplementedException(),
			Enemy.Wardenfly => throw new NotImplementedException(),
			Enemy.Driftlin => throw new NotImplementedException(),
			Enemy.Mnemonid => throw new NotImplementedException(),
			Enemy.Mnemonord => throw new NotImplementedException(),
			Enemy.ServitorIgnim => throw new NotImplementedException(),
			Enemy.ServitorBoran => throw new NotImplementedException(),
			Enemy.WingedLifeseed => throw new NotImplementedException(),
			Enemy.Plasmid => throw new NotImplementedException(),
			Enemy.Plasmidas => throw new NotImplementedException(),
			Enemy.LeafGlider => throw new NotImplementedException(),
			Enemy.LeafRoller => throw new NotImplementedException(),
			Enemy.Pendra => throw new NotImplementedException(),
			Enemy.Pendragor => throw new NotImplementedException(),
			Enemy.Nuphar => throw new NotImplementedException(),
			Enemy.Cloverstag => throw new NotImplementedException(),
			Enemy.Kindanir => throw new NotImplementedException(),
			Enemy.Verdanir => throw new NotImplementedException(),
			Enemy.Escalion => throw new NotImplementedException(),
			Enemy.ShadowCreeper => throw new NotImplementedException(),
			Enemy.ShadowCharger => throw new NotImplementedException(),
			Enemy.Gloomsac => throw new NotImplementedException(),
			Enemy.GargantGloom => throw new NotImplementedException(),
			Enemy.VoidTendrils => throw new NotImplementedException(),
			Enemy.VoidMass => throw new NotImplementedException(),
			Enemy.Wingmould => throw new NotImplementedException(),
			Enemy.Garpid => throw new NotImplementedException(),
			Enemy.Imoba => throw new NotImplementedException(),
			Enemy.Skrill => throw new NotImplementedException(),
			_ => throw new InvalidCheckException<Enemy>(enemy),
		};
	}
}
