using System.Diagnostics.CodeAnalysis;
using Silksong.BingoSync.Data;
using Silksong.BingoSync.Exceptions;

namespace Silksong.BingoSync.Extensions;

/// <summary>
/// Extension methods of <see cref="PlayerData"/> concerning journal entries
/// </summary>
[SuppressMessage("ReSharper", "ConvertToExtensionBlock")]
public static partial class PlayerDataExtensions
{
	/// <summary>
	/// Gets the <see cref="EnemyJournalKillData.KillData"/> of the given key
	/// </summary>
	private static EnemyJournalKillData.KillData GetKillData(this PlayerData data, string key) =>
		data.EnemyJournalKillData.GetKillData(key);

	/// <summary>
	/// Gets the amount of kills of the journal entry of the given key
	/// </summary>
	private static int GetKillCount(this PlayerData data, string key) =>
		data.GetKillData(key).Kills;

	/// <summary>
	/// Checks if a journal entry is set for the given key
	/// </summary>
	private static bool HasObtainedJournalEntry(this PlayerData data, string key) =>
		data.GetKillCount(key) > 0;

	/// <summary>
	/// Checks if the journal entry of the given <see cref="Boss"/> has been obtained
	/// </summary>
	public static bool HasObtainedJournalEntry(this PlayerData data, Boss boss)
	{
		return boss switch
		{
			Boss.Shakra => data.HasObtainedJournalEntry("Shakra"),
			Boss.BellBeast => data.HasObtainedJournalEntry("Bone Beast"),
			Boss.FourthChorus => data.HasObtainedJournalEntry("Song Golem"),
			Boss.GreatConchflies or Boss.RagingConchfly => data.HasObtainedJournalEntry(
				"Coral Conch Driller Giant"
			),
			Boss.Lace1 or Boss.Lace2 => data.HasObtainedJournalEntry("Lace"),
			Boss.LastJudge => data.HasObtainedJournalEntry("Last Judge"),
			Boss.Moorwing => data.HasObtainedJournalEntry("Vampire Gnat"),
			Boss.MossMother => data.HasObtainedJournalEntry("Mossbone Mother"),
			Boss.MossMothers => data.GetKillCount("Mossbone Mother") >= 3,
			Boss.Phantom => data.HasObtainedJournalEntry("Phantom"),
			Boss.SavageBeastfly1 or Boss.SavageBeastfly2 => data.HasObtainedJournalEntry(
				"Bone Flyer Giant"
			),
			Boss.SisterSplinter => data.HasObtainedJournalEntry("Splinter Queen"),
			Boss.SkullTyrant1 => data.HasObtainedJournalEntry("Skull King"),
			Boss.SkullTyrant2 => data.GetKillCount("Skull King") >= 2,
			Boss.Widow => data.HasObtainedJournalEntry("Spinner Boss"),
			Boss.Broodmother => data.HasObtainedJournalEntry("Slab Fly Broodmother"),
			Boss.CogworkDancers => data.HasObtainedJournalEntry("Clockwork Dancer"),
			Boss.DisgracedChefLugoli => data.HasObtainedJournalEntry("Roachkeeper Chef"),
			Boss.FatherOfTheFlame => data.HasObtainedJournalEntry("Wisp Pyre Effigy"),
			Boss.FirstSinner => data.HasObtainedJournalEntry("First Weaver"),
			Boss.Forebrothers => data.HasObtainedJournalEntry("Dock Guard Thrower"),
			Boss.Garmond => data.HasObtainedJournalEntry("Garmond"),
			Boss.GrandMotherSilk => data.HasObtainedJournalEntry("Silk Boss"),
			Boss.Groal => data.HasObtainedJournalEntry("Swamp Shaman"),
			Boss.SecondSentinel => data.HasObtainedJournalEntry("Song Knight"),
			Boss.TheUnravelled => data.HasObtainedJournalEntry("Conductor Boss"),
			Boss.Trobbio => data.HasObtainedJournalEntry("Trobbio"),
			Boss.Voltvyrm => data.HasObtainedJournalEntry("Zap Core Enemy"),
			Boss.BellEater => data.HasObtainedJournalEntry("Giant Centipede"),
			Boss.CloverDancers => data.HasObtainedJournalEntry("Clover Dancer"),
			Boss.Crawfather => data.HasObtainedJournalEntry("Crawfather"),
			Boss.CrustKingKhann => data.HasObtainedJournalEntry("Coral King"),
			Boss.GurrTheOutcast => data.HasObtainedJournalEntry("Bone Hunter Trapper"),
			Boss.LostGarmond => data.HasObtainedJournalEntry("Garmond"),
			Boss.LostLace => data.HasObtainedJournalEntry("Lost Lace"),
			Boss.Nyleth => data.HasObtainedJournalEntry("Flower Queen"),
			Boss.Palestag => data.HasObtainedJournalEntry("Cloverstag White"),
			Boss.Pinstress => data.HasObtainedJournalEntry("Pinstress Boss"),
			Boss.PlasmifiedZango => data.HasObtainedJournalEntry("Blue Assistant"),
			Boss.ShrineGuardianSeth => data.HasObtainedJournalEntry("Seth"),
			Boss.SkarrsingerKarmelita => data.HasObtainedJournalEntry("Hunter Queen"),
			Boss.TormentedTrobbio => data.HasObtainedJournalEntry("Tormented Trobbio"),
			Boss.Watcher => data.HasObtainedJournalEntry("Coral Warrior Grey"),
			_ => throw new InvalidCheckException<Boss>(boss),
		};
	}

	/// <summary>
	/// Checks if the journal entry of the given <see cref="Enemy"/> has been obtained
	/// </summary>
	public static bool HasObtainedJournalEntry(this PlayerData data, Enemy enemy)
	{
		return enemy switch
		{
			Enemy.Mossgrub => data.HasObtainedJournalEntry("MossBone Crawler"),
			Enemy.MassiveMossgrub => data.HasObtainedJournalEntry("MossBone Crawler Fat"),
			Enemy.Mossmir => data.HasObtainedJournalEntry("MossBone Fly"),
			Enemy.Aknid => data.HasObtainedJournalEntry("Aspid Collector"),
			Enemy.SkullScuttler => data.HasObtainedJournalEntry("Bone Goomba"),
			Enemy.Skullwing => data.HasObtainedJournalEntry("Bone Goomba Bounce Fly"),
			Enemy.SkullBrute => data.HasObtainedJournalEntry("Bone Goomba Large"),
			Enemy.Kilik => data.HasObtainedJournalEntry("Bone Crawler"),
			Enemy.Beastfly => data.HasObtainedJournalEntry("Bone Flyer"),
			Enemy.Caranid => data.HasObtainedJournalEntry("Bone Circler"),
			Enemy.ViciousCaranid => data.HasObtainedJournalEntry("Bone Circler Vicious"),
			Enemy.HardboneHopper => data.HasObtainedJournalEntry("Bone Hopper"),
			Enemy.HardboneElder => data.HasObtainedJournalEntry("Bone Hopper Giant"),
			Enemy.Tarmite => data.HasObtainedJournalEntry("Bone Splitter"),
			Enemy.Mawling => data.HasObtainedJournalEntry("Bone Roller"),
			Enemy.Marrowmaw => data.HasObtainedJournalEntry("Bone Thumper"),
			Enemy.Hoker => data.HasObtainedJournalEntry("Spine Floater"),
			Enemy.Flintbeetle => data.HasObtainedJournalEntry("Rock Roller"),
			Enemy.Rhinogrund => data.HasObtainedJournalEntry("Rhino"),
			Enemy.Gromling => data.HasObtainedJournalEntry("Crypt Worm"),
			Enemy.Grom => data.HasObtainedJournalEntry("Bone Worm"),
			Enemy.PilgrimGroveller => data.HasObtainedJournalEntry("Pilgrim 03"),
			Enemy.PilgrimPouncer => data.HasObtainedJournalEntry("Pilgrim 01"),
			Enemy.PilgrimHornfly => data.HasObtainedJournalEntry("Pilgrim 04"),
			Enemy.PilgrimHulk => data.HasObtainedJournalEntry("Pilgrim 02"),
			Enemy.PilgrimBellbearer => data.HasObtainedJournalEntry("Pilgrim Bell Thrower"),
			Enemy.WingedPilgrim => data.HasObtainedJournalEntry("Pilgrim Fly"),
			Enemy.ElderPilgrim => data.HasObtainedJournalEntry("Pilgrim 05"),
			Enemy.WingedPilgrimBellbearer => data.HasObtainedJournalEntry(
				"Pilgrim Bellthrower Fly"
			),
			Enemy.PilgrimHiker => data.HasObtainedJournalEntry("Pilgrim Hiker"),
			Enemy.PilgrimGuide => data.HasObtainedJournalEntry("Pilgrim StaffWielder"),
			Enemy.OvergrownPilgrim => data.HasObtainedJournalEntry("Pilgrim Moss Spitter"),
			Enemy.CovetousPilgrim => data.HasObtainedJournalEntry("Rosary Pilgrim"),
			Enemy.Snitchfly => data.HasObtainedJournalEntry("Rosary Thief"),
			Enemy.Lavalug => data.HasObtainedJournalEntry("Tar Slug"),
			Enemy.Lavalarga => data.HasObtainedJournalEntry("Tar Slug Huge"),
			Enemy.SmeltShoveller => data.HasObtainedJournalEntry("Dock Worker"),
			Enemy.FlintstoneFlyer => data.HasObtainedJournalEntry("Dock Flyer"),
			Enemy.FlintflameFlyer => data.HasObtainedJournalEntry("Dock Bomber"),
			Enemy.SmokerockSifter => data.HasObtainedJournalEntry("Shield Dock Worker"),
			Enemy.DeepDiver => data.HasObtainedJournalEntry("Dock Charger"),
			Enemy.Cragglite => data.HasObtainedJournalEntry("Small Crab"),
			Enemy.Craggler => data.HasObtainedJournalEntry("Roof Crab"),
			Enemy.Brushflit => data.HasObtainedJournalEntry("Fields Flock Flyers"),
			Enemy.Fertid => data.HasObtainedJournalEntry("Fields Goomba"),
			Enemy.FlappingFertid => data.HasObtainedJournalEntry("Fields Flyer"),
			Enemy.Skarrlid => data.HasObtainedJournalEntry("Bone Hunter Tiny"),
			Enemy.Skarrwing => data.HasObtainedJournalEntry("Bone Hunter Buzzer"),
			Enemy.SkarrScout => data.HasObtainedJournalEntry("Bone Hunter Child"),
			Enemy.SkarrStalker => data.HasObtainedJournalEntry("Bone Hunter"),
			Enemy.SpearSkarr => data.HasObtainedJournalEntry("Bone Hunter Fly"),
			Enemy.Skarrgard => data.HasObtainedJournalEntry("Bone Hunter Throw"),
			Enemy.LastClaw => data.HasObtainedJournalEntry("Bone Hunter Chief"),
			Enemy.Mite => data.HasObtainedJournalEntry("Mite"),
			Enemy.Fluttermite => data.HasObtainedJournalEntry("Mitefly"),
			Enemy.Mitemother => data.HasObtainedJournalEntry("Gnat Giant"),
			Enemy.DregCatcher => data.HasObtainedJournalEntry("Farmer Catcher"),
			Enemy.SilkSnipper => data.HasObtainedJournalEntry("Farmer Scissors"),
			Enemy.ThreadRaker => data.HasObtainedJournalEntry("Farmer Centipede"),
			Enemy.Wisp => data.HasObtainedJournalEntry("Wisp"),
			Enemy.BurningBug => data.HasObtainedJournalEntry("Farmer Wisp"),
			Enemy.Craw => data.HasObtainedJournalEntry("Crow"),
			Enemy.Tallcraw => data.HasObtainedJournalEntry("Crowman"),
			Enemy.Squatcraw => data.HasObtainedJournalEntry("Crowman Dagger"),
			Enemy.CrawJuror => data.HasObtainedJournalEntry("Crowman Juror Tiny"),
			Enemy.TallcrawJuror => data.HasObtainedJournalEntry("Crowman Juror"),
			Enemy.SquatcrawJuror => data.HasObtainedJournalEntry("Crowman Dagger Juror"),
			Enemy.Muckmaggot => data.HasObtainedJournalEntry("Maggots"),
			Enemy.Slubberlug => data.HasObtainedJournalEntry("Dustroach Pollywog"),
			Enemy.Muckroach => data.HasObtainedJournalEntry("Dustroach"),
			Enemy.Bloatroach => data.HasObtainedJournalEntry("Bloat Roach"),
			Enemy.Roachcatcher => data.HasObtainedJournalEntry("Roachfeeder Short"),
			Enemy.Roachfeeder => data.HasObtainedJournalEntry("Roachfeeder Tall"),
			Enemy.Roachkeeper => data.HasObtainedJournalEntry("Roachkeeper"),
			Enemy.Roachserver => data.HasObtainedJournalEntry("Roachkeeper Chef Tiny"),
			Enemy.Wraith => data.HasObtainedJournalEntry("Wraith"),
			Enemy.MothleafLagnia => data.HasObtainedJournalEntry("Swamp Drifter"),
			Enemy.Miremite => data.HasObtainedJournalEntry("Swamp Goomba"),
			Enemy.SwampSquit => data.HasObtainedJournalEntry("Swamp Mosquito"),
			Enemy.SpitSquit => data.HasObtainedJournalEntry("Swamp Mosquito Skinny"),
			Enemy.Stilkin => data.HasObtainedJournalEntry("Swamp Muckman"),
			Enemy.StilkinTrapper => data.HasObtainedJournalEntry("Swamp Muckman Tall"),
			Enemy.Barnak => data.HasObtainedJournalEntry("Swamp Barnacle"),
			Enemy.Ductsucker => data.HasObtainedJournalEntry("Swamp Ductsucker"),
			Enemy.PondSkipper => data.HasObtainedJournalEntry("Pond Skater"),
			Enemy.Pondcatcher => data.HasObtainedJournalEntry("Pilgrim Fisher"),
			Enemy.ShellwoodGnat => data.HasObtainedJournalEntry("Shellwood Gnat"),
			Enemy.WoodWasp => data.HasObtainedJournalEntry("Shellwood Wasp"),
			Enemy.Splinter => data.HasObtainedJournalEntry("Stick Insect"),
			Enemy.Splinterhorn => data.HasObtainedJournalEntry("Stick Insect Charger"),
			Enemy.Splinterbark => data.HasObtainedJournalEntry("Stick Insect Flyer"),
			Enemy.Phacia => data.HasObtainedJournalEntry("Flower Drifter"),
			Enemy.Pollenica => data.HasObtainedJournalEntry("Bloom Shooter"),
			Enemy.Gahlia => data.HasObtainedJournalEntry("Bloom Puncher"),
			Enemy.Furm => data.HasObtainedJournalEntry("Bell Goomba"),
			Enemy.WingedFurm => data.HasObtainedJournalEntry("Bell Fly"),
			Enemy.Pharlid => data.HasObtainedJournalEntry("Blade Spider"),
			Enemy.PharlidDiver => data.HasObtainedJournalEntry("Blade Spider Hang"),
			Enemy.Shardillard => data.HasObtainedJournalEntry("Shell Fossil Mimic"),
			Enemy.Sandcarver => data.HasObtainedJournalEntry("Sand Centipede"),
			Enemy.Squirrm => data.HasObtainedJournalEntry("Coral Judge Child"),
			Enemy.Judge => data.HasObtainedJournalEntry("Coral Judge"),
			Enemy.CoralFurm => data.HasObtainedJournalEntry("Coral Spike Goomba"),
			Enemy.Driznit => data.HasObtainedJournalEntry("Coral Conch Shooter"),
			Enemy.Driznarga => data.HasObtainedJournalEntry("Coral Conch Shooter Heavy"),
			Enemy.Pokenabbin => data.HasObtainedJournalEntry("Coral Conch Stabber"),
			Enemy.Conchfly => data.HasObtainedJournalEntry("Coral Conch Driller"),
			Enemy.Crustcrawler => data.HasObtainedJournalEntry("Coral Goombas"),
			Enemy.Crustcrag => data.HasObtainedJournalEntry("Coral Goomba Large"),
			Enemy.Kai => data.HasObtainedJournalEntry("Coral Swimmer Fat"),
			Enemy.SpinebeakKai => data.HasObtainedJournalEntry("Poke Swimmer"),
			Enemy.SteelspineKai => data.HasObtainedJournalEntry("Spike Swimmer"),
			Enemy.Yuma => data.HasObtainedJournalEntry("Coral Swimmer Small"),
			Enemy.Yumama => data.HasObtainedJournalEntry("Coral Big Jellyfish"),
			Enemy.Karaka => data.HasObtainedJournalEntry("Coral Warrior"),
			Enemy.Kakri => data.HasObtainedJournalEntry("Coral Flyer"),
			Enemy.Yago => data.HasObtainedJournalEntry("Coral Flyer Throw"),
			Enemy.KarakGor => data.HasObtainedJournalEntry("Coral Brawler"),
			Enemy.Alita => data.HasObtainedJournalEntry("Coral Hunter"),
			Enemy.CorrcrustKaraka => data.HasObtainedJournalEntry("Coral Bubble Brute"),
			Enemy.Drapefly => data.HasObtainedJournalEntry("Citadel Bat"),
			Enemy.Drapelord => data.HasObtainedJournalEntry("Citadel Bat Large"),
			Enemy.Drapemite => data.HasObtainedJournalEntry("Mite Heavy"),
			Enemy.GiantDrapemite => data.HasObtainedJournalEntry("Understore Mite Giant"),
			Enemy.Underworker => data.HasObtainedJournalEntry("Understore Small"),
			Enemy.Underscrub => data.HasObtainedJournalEntry("Pilgrim 03 Understore"),
			Enemy.Undersweep => data.HasObtainedJournalEntry("Pilgrim Staff Understore"),
			Enemy.Underpoke => data.HasObtainedJournalEntry("Understore Poker"),
			Enemy.Underloft => data.HasObtainedJournalEntry("Understore Thrower"),
			Enemy.Undercrank => data.HasObtainedJournalEntry("Understore Heavy"),
			Enemy.Envoy => data.HasObtainedJournalEntry("Song Pilgrim 01"),
			Enemy.ChoirPouncer => data.HasObtainedJournalEntry("Pilgrim 01 Song"),
			Enemy.ChoirHornhead => data.HasObtainedJournalEntry("Pilgrim 02 Song"),
			Enemy.ChoirBellbearer => data.HasObtainedJournalEntry("Pilgrim 03 Song"),
			Enemy.ChoirFlyer => data.HasObtainedJournalEntry("Pilgrim 04 Song"),
			Enemy.ChoirElder => data.HasObtainedJournalEntry("Pilgrim Stomper Song"),
			Enemy.Choristor => data.HasObtainedJournalEntry("Song Pilgrim 03"),
			Enemy.Reed => data.HasObtainedJournalEntry("Song Reed"),
			Enemy.GrandReed => data.HasObtainedJournalEntry("Song Reed Grand"),
			Enemy.ChoirClapper => data.HasObtainedJournalEntry("Song Heavy Sentry"),
			Enemy.Clawmaiden => data.HasObtainedJournalEntry("Song Handmaiden"),
			Enemy.Memoria => data.HasObtainedJournalEntry("Arborium Keeper"),
			Enemy.Minister => data.HasObtainedJournalEntry("Song Administrator"),
			Enemy.Maestro => data.HasObtainedJournalEntry("Song Pilgrim Maestro"),
			Enemy.DregHusk => data.HasObtainedJournalEntry("Song Threaded Husk"),
			Enemy.Dregwheel => data.HasObtainedJournalEntry("Song Threaded Husk Spin"),
			Enemy.Surgeon => data.HasObtainedJournalEntry("Song Pilgrim 02"),
			Enemy.Mortician => data.HasObtainedJournalEntry("Song Creeper"),
			Enemy.CogworkUnderfly => data.HasObtainedJournalEntry("Understore Automaton"),
			Enemy.CogworkHauler => data.HasObtainedJournalEntry("Understore Automaton EX"),
			Enemy.CogworkCrawler => data.HasObtainedJournalEntry("Song Automaton Goomba"),
			Enemy.Cogworker => data.HasObtainedJournalEntry("Song Automaton Fly"),
			Enemy.CogworkSpine => data.HasObtainedJournalEntry("Song Automaton Fly Spike"),
			Enemy.CogworkChoirbug => data.HasObtainedJournalEntry("Song Automaton 01"),
			Enemy.CogworkCleanser => data.HasObtainedJournalEntry("Song Automaton 02"),
			Enemy.CogworkDefender => data.HasObtainedJournalEntry("Song Automaton Shield"),
			Enemy.CogworkClapper => data.HasObtainedJournalEntry("Song Automaton Ball"),
			Enemy.Vaultborn => data.HasObtainedJournalEntry("Song Scholar Acolyte"),
			Enemy.Lampbearer => data.HasObtainedJournalEntry("Lightbearer"),
			Enemy.Scrollreader => data.HasObtainedJournalEntry("Scrollkeeper"),
			Enemy.Vaultkeeper => data.HasObtainedJournalEntry("Scholar"),
			Enemy.Penitent => data.HasObtainedJournalEntry("Slab Prisoner Leaper New"),
			Enemy.PunyPenitent => data.HasObtainedJournalEntry("Slab Prisoner Fly New"),
			Enemy.Freshfly => data.HasObtainedJournalEntry("Slab Fly Small Fresh"),
			Enemy.Scabfly => data.HasObtainedJournalEntry("Slab Fly Small"),
			Enemy.Guardfly => data.HasObtainedJournalEntry("Slab Fly Mid"),
			Enemy.Wardenfly => data.HasObtainedJournalEntry("Slab Fly Large"),
			Enemy.Driftlin => data.HasObtainedJournalEntry("Peaks Drifter"),
			Enemy.Mnemonid => data.HasObtainedJournalEntry("Crystal Drifter"),
			Enemy.Mnemonord => data.HasObtainedJournalEntry("Crystal Drifter Giant"),
			Enemy.ServitorIgnim => data.HasObtainedJournalEntry("Weaver Servitor"),
			Enemy.ServitorBoran => data.HasObtainedJournalEntry("Weaver Servitor Large"),
			Enemy.WingedLifeseed => data.HasObtainedJournalEntry("Lifeblood Fly"),
			Enemy.Plasmid => data.HasObtainedJournalEntry("Bone Worm BlueBlood"),
			Enemy.Plasmidas => data.HasObtainedJournalEntry("Bone Worm BlueTurret"),
			Enemy.LeafGlider => data.HasObtainedJournalEntry("Lilypad Fly"),
			Enemy.LeafRoller => data.HasObtainedJournalEntry("Grass Goomba"),
			Enemy.Pendra => data.HasObtainedJournalEntry("Hornet Dragonfly"),
			Enemy.Pendragor => data.HasObtainedJournalEntry("Dragonfly Large"),
			Enemy.Nuphar => data.HasObtainedJournalEntry("Lilypad Trap"),
			Enemy.Cloverstag => data.HasObtainedJournalEntry("Cloverstag"),
			Enemy.Kindanir => data.HasObtainedJournalEntry("Grasshopper Child"),
			Enemy.Verdanir => data.HasObtainedJournalEntry("Grasshopper Slasher"),
			Enemy.Escalion => data.HasObtainedJournalEntry("Grasshopper Fly"),
			Enemy.ShadowCreeper => data.HasObtainedJournalEntry("Abyss Crawler"),
			Enemy.ShadowCharger => data.HasObtainedJournalEntry("Abyss Crawler Large"),
			Enemy.Gloomsac => data.HasObtainedJournalEntry("Gloomfly"),
			Enemy.GargantGloom => data.HasObtainedJournalEntry("Gloom Beast"),
			Enemy.VoidTendrils => data.HasObtainedJournalEntry("Void Tendrils"),
			Enemy.VoidMass => data.HasObtainedJournalEntry("Black Thread Core"),
			Enemy.Wingmould => data.HasObtainedJournalEntry("White Palace Fly"),
			Enemy.Garpid => data.HasObtainedJournalEntry("Centipede Trap"),
			Enemy.Imoba => data.HasObtainedJournalEntry("Spike Lazy Flyer"),
			Enemy.Skrill => data.HasObtainedJournalEntry("Surface Scuttler"),
			_ => throw new InvalidCheckException<Enemy>(enemy),
		};
	}
}
