using System.Diagnostics.CodeAnalysis;
using Silksong.BingoSync.Data;
using Silksong.BingoSync.Exceptions;

namespace Silksong.BingoSync.Extensions;

/// <summary>
/// Extension methods of <see cref="PlayerData"/> concerning journal entries
/// </summary>
[SuppressMessage("ReSharper", "ConvertToExtensionBlock")]
public static partial class PlayerDataExtensions
{
	/// <summary>
	/// Gets the <see cref="EnemyJournalKillData.KillData"/> of the given key
	/// </summary>
	private static EnemyJournalKillData.KillData GetKillData(this PlayerData data, string key) =>
		data.EnemyJournalKillData.GetKillData(key);

	/// <summary>
	/// Gets the amount of kills of the journal entry of the given key
	/// </summary>
	private static int GetKillCount(this PlayerData data, string key) =>
		data.GetKillData(key).Kills;

	/// <summary>
	/// Checks if a journal entry is set for the given key
	/// </summary>
	private static bool HasJournalEntry(this PlayerData data, string key) =>
		data.GetKillCount(key) > 0;

	/// <summary>
	/// Checks if the journal entry of the given <see cref="Boss"/> has been obtained
	/// </summary>
	public static bool HasObtainedJournalEntry(this PlayerData data, Boss boss)
	{
		return boss switch
		{
			Boss.Shakra => data.HasJournalEntry("Shakra"),
			Boss.BellBeast => data.HasJournalEntry("Bone Beast"),
			Boss.FourthChorus => data.HasJournalEntry("Song Golem"),
			Boss.GreatConchflies or Boss.RagingConchfly => data.HasJournalEntry(
				"Coral Conch Driller Giant"
			),
			Boss.Lace1 or Boss.Lace2 => data.HasJournalEntry("Lace"),
			Boss.LastJudge => data.HasJournalEntry("Last Judge"),
			Boss.Moorwing => data.HasJournalEntry("Vampire Gnat"),
			Boss.MossMother => data.HasJournalEntry("Mossbone Mother"),
			Boss.MossMothers => data.GetKillCount("Mossbone Mother") >= 3,
			Boss.Phantom => data.HasJournalEntry("Phantom"),
			Boss.SavageBeastfly1 or Boss.SavageBeastfly2 => data.HasJournalEntry(
				"Bone Flyer Giant"
			),
			Boss.SisterSplinter => data.HasJournalEntry("Splinter Queen"),
			Boss.SkullTyrant1 => data.HasJournalEntry("Skull King"),
			Boss.SkullTyrant2 => data.GetKillCount("Skull King") >= 2,
			Boss.Widow => data.HasJournalEntry("Spinner Boss"),
			Boss.Broodmother => data.HasJournalEntry("Slab Fly Broodmother"),
			Boss.CogworkDancers => data.HasJournalEntry("Clockwork Dancer"),
			Boss.DisgracedChefLugoli => data.HasJournalEntry("Roachkeeper Chef"),
			Boss.FatherOfTheFlame => data.HasJournalEntry("Wisp Pyre Effigy"),
			Boss.FirstSinner => data.HasJournalEntry("First Weaver"),
			Boss.Forebrothers => data.HasJournalEntry("Dock Guard Thrower"),
			Boss.Garmond => data.HasJournalEntry("Garmond"),
			Boss.GrandMotherSilk => data.HasJournalEntry("Silk Boss"),
			Boss.Groal => data.HasJournalEntry("Swamp Shaman"),
			Boss.SecondSentinel => data.HasJournalEntry("Song Knight"),
			Boss.TheUnravelled => data.HasJournalEntry("Conductor Boss"),
			Boss.Trobbio => data.HasJournalEntry("Trobbio"),
			Boss.Voltvyrm => data.HasJournalEntry("Zap Core Enemy"),
			Boss.BellEater => data.HasJournalEntry("Giant Centipede"),
			Boss.CloverDancers => data.HasJournalEntry("Clover Dancer"),
			Boss.Crawfather => data.HasJournalEntry("Crawfather"),
			Boss.CrustKingKhann => data.HasJournalEntry("Coral King"),
			Boss.GurrTheOutcast => data.HasJournalEntry("Bone Hunter Trapper"),
			Boss.LostGarmond => data.HasJournalEntry("Garmond"),
			Boss.LostLace => data.HasJournalEntry("Lost Lace"),
			Boss.Nyleth => data.HasJournalEntry("Flower Queen"),
			Boss.Palestag => data.HasJournalEntry("Cloverstag White"),
			Boss.Pinstress => data.HasJournalEntry("Pinstress Boss"),
			Boss.PlasmifiedZango => data.HasJournalEntry("Blue Assistant"),
			Boss.ShrineGuardianSeth => data.HasJournalEntry("Seth"),
			Boss.SkarrsingerKarmelita => data.HasJournalEntry("Hunter Queen"),
			Boss.TormentedTrobbio => data.HasJournalEntry("Tormented Trobbio"),
			Boss.Watcher => data.HasJournalEntry("Coral Warrior Grey"),
			_ => throw new InvalidCheckException<Boss>(boss),
		};
	}

	/// <summary>
	/// Checks if the journal entry of the given <see cref="Enemy"/> has been obtained
	/// </summary>
	public static bool HasObtainedJournalEntry(this PlayerData data, Enemy enemy)
	{
		return enemy switch
		{
			Enemy.Mossgrub => data.HasJournalEntry("MossBone Crawler"),
			Enemy.MassiveMossgrub => data.HasJournalEntry("MossBone Crawler Fat"),
			Enemy.Mossmir => data.HasJournalEntry("MossBone Fly"),
			Enemy.Aknid => data.HasJournalEntry("Aspid Collector"),
			Enemy.SkullScuttler => data.HasJournalEntry("Bone Goomba"),
			Enemy.Skullwing => data.HasJournalEntry("Bone Goomba Bounce Fly"),
			Enemy.SkullBrute => data.HasJournalEntry("Bone Goomba Large"),
			Enemy.Kilik => data.HasJournalEntry("Bone Crawler"),
			Enemy.Beastfly => data.HasJournalEntry("Bone Flyer"),
			Enemy.Caranid => data.HasJournalEntry("Bone Circler"),
			Enemy.ViciousCaranid => data.HasJournalEntry("Bone Circler Vicious"),
			Enemy.HardboneHopper => data.HasJournalEntry("Bone Hopper"),
			Enemy.HardboneElder => data.HasJournalEntry("Bone Hopper Giant"),
			Enemy.Tarmite => data.HasJournalEntry("Bone Splitter"),
			Enemy.Mawling => data.HasJournalEntry("Bone Roller"),
			Enemy.Marrowmaw => data.HasJournalEntry("Bone Thumper"),
			Enemy.Hoker => data.HasJournalEntry("Spine Floater"),
			Enemy.Flintbeetle => data.HasJournalEntry("Rock Roller"),
			Enemy.Rhinogrund => data.HasJournalEntry("Rhino"),
			Enemy.Gromling => data.HasJournalEntry("Crypt Worm"),
			Enemy.Grom => data.HasJournalEntry("Bone Worm"),
			Enemy.PilgrimGroveller => data.HasJournalEntry("Pilgrim 03"),
			Enemy.PilgrimPouncer => data.HasJournalEntry("Pilgrim 01"),
			Enemy.PilgrimHornfly => data.HasJournalEntry("Pilgrim 04"),
			Enemy.PilgrimHulk => data.HasJournalEntry("Pilgrim 02"),
			Enemy.PilgrimBellbearer => data.HasJournalEntry("Pilgrim Bell Thrower"),
			Enemy.WingedPilgrim => data.HasJournalEntry("Pilgrim Fly"),
			Enemy.ElderPilgrim => data.HasJournalEntry("Pilgrim 05"),
			Enemy.WingedPilgrimBellbearer => data.HasJournalEntry("Pilgrim Bellthrower Fly"),
			Enemy.PilgrimHiker => data.HasJournalEntry("Pilgrim Hiker"),
			Enemy.PilgrimGuide => data.HasJournalEntry("Pilgrim StaffWielder"),
			Enemy.OvergrownPilgrim => data.HasJournalEntry("Pilgrim Moss Spitter"),
			Enemy.CovetousPilgrim => data.HasJournalEntry("Rosary Pilgrim"),
			Enemy.Snitchfly => data.HasJournalEntry("Rosary Thief"),
			Enemy.Lavalug => data.HasJournalEntry("Tar Slug"),
			Enemy.Lavalarga => data.HasJournalEntry("Tar Slug Huge"),
			Enemy.SmeltShoveller => data.HasJournalEntry("Dock Worker"),
			Enemy.FlintstoneFlyer => data.HasJournalEntry("Dock Flyer"),
			Enemy.FlintflameFlyer => data.HasJournalEntry("Dock Bomber"),
			Enemy.SmokerockSifter => data.HasJournalEntry("Shield Dock Worker"),
			Enemy.DeepDiver => data.HasJournalEntry("Dock Charger"),
			Enemy.Cragglite => data.HasJournalEntry("Small Crab"),
			Enemy.Craggler => data.HasJournalEntry("Roof Crab"),
			Enemy.Brushflit => data.HasJournalEntry("Fields Flock Flyers"),
			Enemy.Fertid => data.HasJournalEntry("Fields Goomba"),
			Enemy.FlappingFertid => data.HasJournalEntry("Fields Flyer"),
			Enemy.Skarrlid => data.HasJournalEntry("Bone Hunter Tiny"),
			Enemy.Skarrwing => data.HasJournalEntry("Bone Hunter Buzzer"),
			Enemy.SkarrScout => data.HasJournalEntry("Bone Hunter Child"),
			Enemy.SkarrStalker => data.HasJournalEntry("Bone Hunter"),
			Enemy.SpearSkarr => data.HasJournalEntry("Bone Hunter Fly"),
			Enemy.Skarrgard => data.HasJournalEntry("Bone Hunter Throw"),
			Enemy.LastClaw => data.HasJournalEntry("Bone Hunter Chief"),
			Enemy.Mite => data.HasJournalEntry("Mite"),
			Enemy.Fluttermite => data.HasJournalEntry("Mitefly"),
			Enemy.Mitemother => data.HasJournalEntry("Gnat Giant"),
			Enemy.DregCatcher => data.HasJournalEntry("Farmer Catcher"),
			Enemy.SilkSnipper => data.HasJournalEntry("Farmer Scissors"),
			Enemy.ThreadRaker => data.HasJournalEntry("Farmer Centipede"),
			Enemy.Wisp => data.HasJournalEntry("Wisp"),
			Enemy.BurningBug => data.HasJournalEntry("Farmer Wisp"),
			Enemy.Craw => data.HasJournalEntry("Crow"),
			Enemy.Tallcraw => data.HasJournalEntry("Crowman"),
			Enemy.Squatcraw => data.HasJournalEntry("Crowman Dagger"),
			Enemy.CrawJuror => data.HasJournalEntry("Crowman Juror Tiny"),
			Enemy.TallcrawJuror => data.HasJournalEntry("Crowman Juror"),
			Enemy.SquatcrawJuror => data.HasJournalEntry("Crowman Dagger Juror"),
			Enemy.Muckmaggot => data.HasJournalEntry("Maggots"),
			Enemy.Slubberlug => data.HasJournalEntry("Dustroach Pollywog"),
			Enemy.Muckroach => data.HasJournalEntry("Dustroach"),
			Enemy.Bloatroach => data.HasJournalEntry("Bloat Roach"),
			Enemy.Roachcatcher => data.HasJournalEntry("Roachfeeder Short"),
			Enemy.Roachfeeder => data.HasJournalEntry("Roachfeeder Tall"),
			Enemy.Roachkeeper => data.HasJournalEntry("Roachkeeper"),
			Enemy.Roachserver => data.HasJournalEntry("Roachkeeper Chef Tiny"),
			Enemy.Wraith => data.HasJournalEntry("Wraith"),
			Enemy.MothleafLagnia => data.HasJournalEntry("Swamp Drifter"),
			Enemy.Miremite => data.HasJournalEntry("Swamp Goomba"),
			Enemy.SwampSquit => data.HasJournalEntry("Swamp Mosquito"),
			Enemy.SpitSquit => data.HasJournalEntry("Swamp Mosquito Skinny"),
			Enemy.Stilkin => data.HasJournalEntry("Swamp Muckman"),
			Enemy.StilkinTrapper => data.HasJournalEntry("Swamp Muckman Tall"),
			Enemy.Barnak => data.HasJournalEntry("Swamp Barnacle"),
			Enemy.Ductsucker => data.HasJournalEntry("Swamp Ductsucker"),
			Enemy.PondSkipper => data.HasJournalEntry("Pond Skater"),
			Enemy.Pondcatcher => data.HasJournalEntry("Pilgrim Fisher"),
			Enemy.ShellwoodGnat => data.HasJournalEntry("Shellwood Gnat"),
			Enemy.WoodWasp => data.HasJournalEntry("Shellwood Wasp"),
			Enemy.Splinter => data.HasJournalEntry("Stick Insect"),
			Enemy.Splinterhorn => data.HasJournalEntry("Stick Insect Charger"),
			Enemy.Splinterbark => data.HasJournalEntry("Stick Insect Flyer"),
			Enemy.Phacia => data.HasJournalEntry("Flower Drifter"),
			Enemy.Pollenica => data.HasJournalEntry("Bloom Shooter"),
			Enemy.Gahlia => data.HasJournalEntry("Bloom Puncher"),
			Enemy.Furm => data.HasJournalEntry("Bell Goomba"),
			Enemy.WingedFurm => data.HasJournalEntry("Bell Fly"),
			Enemy.Pharlid => data.HasJournalEntry("Blade Spider"),
			Enemy.PharlidDiver => data.HasJournalEntry("Blade Spider Hang"),
			Enemy.Shardillard => data.HasJournalEntry("Shell Fossil Mimic"),
			Enemy.Sandcarver => data.HasJournalEntry("Sand Centipede"),
			Enemy.Squirrm => data.HasJournalEntry("Coral Judge Child"),
			Enemy.Judge => data.HasJournalEntry("Coral Judge"),
			Enemy.CoralFurm => data.HasJournalEntry("Coral Spike Goomba"),
			Enemy.Driznit => data.HasJournalEntry("Coral Conch Shooter"),
			Enemy.Driznarga => data.HasJournalEntry("Coral Conch Shooter Heavy"),
			Enemy.Pokenabbin => data.HasJournalEntry("Coral Conch Stabber"),
			Enemy.Conchfly => data.HasJournalEntry("Coral Conch Driller"),
			Enemy.Crustcrawler => data.HasJournalEntry("Coral Goombas"),
			Enemy.Crustcrag => data.HasJournalEntry("Coral Goomba Large"),
			Enemy.Kai => data.HasJournalEntry("Coral Swimmer Fat"),
			Enemy.SpinebeakKai => data.HasJournalEntry("Poke Swimmer"),
			Enemy.SteelspineKai => data.HasJournalEntry("Spike Swimmer"),
			Enemy.Yuma => data.HasJournalEntry("Coral Swimmer Small"),
			Enemy.Yumama => data.HasJournalEntry("Coral Big Jellyfish"),
			Enemy.Karaka => data.HasJournalEntry("Coral Warrior"),
			Enemy.Kakri => data.HasJournalEntry("Coral Flyer"),
			Enemy.Yago => data.HasJournalEntry("Coral Flyer Throw"),
			Enemy.KarakGor => data.HasJournalEntry("Coral Brawler"),
			Enemy.Alita => data.HasJournalEntry("Coral Hunter"),
			Enemy.CorrcrustKaraka => data.HasJournalEntry("Coral Bubble Brute"),
			Enemy.Drapefly => data.HasJournalEntry("Citadel Bat"),
			Enemy.Drapelord => data.HasJournalEntry("Citadel Bat Large"),
			Enemy.Drapemite => data.HasJournalEntry("Mite Heavy"),
			Enemy.GiantDrapemite => data.HasJournalEntry("Understore Mite Giant"),
			Enemy.Underworker => data.HasJournalEntry("Understore Small"),
			Enemy.Underscrub => data.HasJournalEntry("Pilgrim 03 Understore"),
			Enemy.Undersweep => data.HasJournalEntry("Pilgrim Staff Understore"),
			Enemy.Underpoke => data.HasJournalEntry("Understore Poker"),
			Enemy.Underloft => data.HasJournalEntry("Understore Thrower"),
			Enemy.Undercrank => data.HasJournalEntry("Understore Heavy"),
			Enemy.Envoy => data.HasJournalEntry("Song Pilgrim 01"),
			Enemy.ChoirPouncer => data.HasJournalEntry("Pilgrim 01 Song"),
			Enemy.ChoirHornhead => data.HasJournalEntry("Pilgrim 02 Song"),
			Enemy.ChoirBellbearer => data.HasJournalEntry("Pilgrim 03 Song"),
			Enemy.ChoirFlyer => data.HasJournalEntry("Pilgrim 04 Song"),
			Enemy.ChoirElder => data.HasJournalEntry("Pilgrim Stomper Song"),
			Enemy.Choristor => data.HasJournalEntry("Song Pilgrim 03"),
			Enemy.Reed => data.HasJournalEntry("Song Reed"),
			Enemy.GrandReed => data.HasJournalEntry("Song Reed Grand"),
			Enemy.ChoirClapper => data.HasJournalEntry("Song Heavy Sentry"),
			Enemy.Clawmaiden => data.HasJournalEntry("Song Handmaiden"),
			Enemy.Memoria => data.HasJournalEntry("Arborium Keeper"),
			Enemy.Minister => data.HasJournalEntry("Song Administrator"),
			Enemy.Maestro => data.HasJournalEntry("Song Pilgrim Maestro"),
			Enemy.DregHusk => data.HasJournalEntry("Song Threaded Husk"),
			Enemy.Dregwheel => data.HasJournalEntry("Song Threaded Husk Spin"),
			Enemy.Surgeon => data.HasJournalEntry("Song Pilgrim 02"),
			Enemy.Mortician => data.HasJournalEntry("Song Creeper"),
			Enemy.CogworkUnderfly => data.HasJournalEntry("Understore Automaton"),
			Enemy.CogworkHauler => data.HasJournalEntry("Understore Automaton EX"),
			Enemy.CogworkCrawler => data.HasJournalEntry("Song Automaton Goomba"),
			Enemy.Cogworker => data.HasJournalEntry("Song Automaton Fly"),
			Enemy.CogworkSpine => data.HasJournalEntry("Song Automaton Fly Spike"),
			Enemy.CogworkChoirbug => data.HasJournalEntry("Song Automaton 01"),
			Enemy.CogworkCleanser => data.HasJournalEntry("Song Automaton 02"),
			Enemy.CogworkDefender => data.HasJournalEntry("Song Automaton Shield"),
			Enemy.CogworkClapper => data.HasJournalEntry("Song Automaton Ball"),
			Enemy.Vaultborn => data.HasJournalEntry("Song Scholar Acolyte"),
			Enemy.Lampbearer => data.HasJournalEntry("Lightbearer"),
			Enemy.Scrollreader => data.HasJournalEntry("Scrollkeeper"),
			Enemy.Vaultkeeper => data.HasJournalEntry("Scholar"),
			Enemy.Penitent => data.HasJournalEntry("Slab Prisoner Leaper New"),
			Enemy.PunyPenitent => data.HasJournalEntry("Slab Prisoner Fly New"),
			Enemy.Freshfly => data.HasJournalEntry("Slab Fly Small Fresh"),
			Enemy.Scabfly => data.HasJournalEntry("Slab Fly Small"),
			Enemy.Guardfly => data.HasJournalEntry("Slab Fly Mid"),
			Enemy.Wardenfly => data.HasJournalEntry("Slab Fly Large"),
			Enemy.Driftlin => data.HasJournalEntry("Peaks Drifter"),
			Enemy.Mnemonid => data.HasJournalEntry("Crystal Drifter"),
			Enemy.Mnemonord => data.HasJournalEntry("Crystal Drifter Giant"),
			Enemy.ServitorIgnim => data.HasJournalEntry("Weaver Servitor"),
			Enemy.ServitorBoran => data.HasJournalEntry("Weaver Servitor Large"),
			Enemy.WingedLifeseed => data.HasJournalEntry("Lifeblood Fly"),
			Enemy.Plasmid => data.HasJournalEntry("Bone Worm BlueBlood"),
			Enemy.Plasmidas => data.HasJournalEntry("Bone Worm BlueTurret"),
			Enemy.LeafGlider => data.HasJournalEntry("Lilypad Fly"),
			Enemy.LeafRoller => data.HasJournalEntry("Grass Goomba"),
			Enemy.Pendra => data.HasJournalEntry("Hornet Dragonfly"),
			Enemy.Pendragor => data.HasJournalEntry("Dragonfly Large"),
			Enemy.Nuphar => data.HasJournalEntry("Lilypad Trap"),
			Enemy.Cloverstag => data.HasJournalEntry("Cloverstag"),
			Enemy.Kindanir => data.HasJournalEntry("Grasshopper Child"),
			Enemy.Verdanir => data.HasJournalEntry("Grasshopper Slasher"),
			Enemy.Escalion => data.HasJournalEntry("Grasshopper Fly"),
			Enemy.ShadowCreeper => data.HasJournalEntry("Abyss Crawler"),
			Enemy.ShadowCharger => data.HasJournalEntry("Abyss Crawler Large"),
			Enemy.Gloomsac => data.HasJournalEntry("Gloomfly"),
			Enemy.GargantGloom => data.HasJournalEntry("Gloom Beast"),
			Enemy.VoidTendrils => data.HasJournalEntry("Void Tendrils"),
			Enemy.VoidMass => data.HasJournalEntry("Black Thread Core"),
			Enemy.Wingmould => data.HasJournalEntry("White Palace Fly"),
			Enemy.Garpid => data.HasJournalEntry("Centipede Trap"),
			Enemy.Imoba => data.HasJournalEntry("Spike Lazy Flyer"),
			Enemy.Skrill => data.HasJournalEntry("Surface Scuttler"),
			_ => throw new InvalidCheckException<Enemy>(enemy),
		};
	}
}
